# Rive harfbuzz Implementation
#
# Rive uses their own fork, see:
#  - https://github.com/rive-app/harfbuzz

# Fetch the Rive repo with FetchContent so that we can
# evaluate the include directory at configure time.
FetchContent_Declare(rive-harfbuzz-download
        # Fetch the latest sources from the Rive Github repository.
        GIT_REPOSITORY "https://github.com/rive-app/harfbuzz.git"
        GIT_TAG rive_8.4.0
)

# Fetch the Rive content if necessary.
FetchContent_GetProperties(rive-harfbuzz-download)
if(NOT rive-harfbuzz-download_POPULATED)
    FetchContent_Populate(rive-harfbuzz-download)
endif()

# ref: https://github.com/rive-app/rive-cpp/blob/6ecd5882959edd42d0e78785800216ec4c7588e2/dependencies/premake5_harfbuzz.lua#L18
add_library(rive-harfbuzz STATIC
        # for i in **/*.{hh,cc}; do [ -f "$i" ] && echo "\${rive-harfbuzz-download_SOURCE_DIR}/src/$i"; done | sort

        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Color/CBDT/CBDT.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Color/COLR/COLR.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Color/COLR/colrv1-closure.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Color/CPAL/CPAL.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Color/sbix/sbix.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Color/svg/svg.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/Common/Coverage.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/Common/CoverageFormat1.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/Common/CoverageFormat2.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/Common/RangeRecord.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GDEF/GDEF.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/Anchor.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/AnchorFormat1.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/AnchorFormat2.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/AnchorFormat3.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/AnchorMatrix.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/ChainContextPos.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/Common.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/ContextPos.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/CursivePos.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/CursivePosFormat1.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/ExtensionPos.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/GPOS.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/LigatureArray.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/MarkArray.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/MarkBasePos.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/MarkBasePosFormat1.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/MarkLigPos.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/MarkLigPosFormat1.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/MarkMarkPos.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/MarkMarkPosFormat1.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/MarkRecord.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/PairPos.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/PairPosFormat1.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/PairPosFormat2.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/PairSet.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/PairValueRecord.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/PosLookup.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/PosLookupSubTable.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/SinglePos.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/SinglePosFormat1.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/SinglePosFormat2.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GPOS/ValueFormat.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GSUB/AlternateSet.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GSUB/AlternateSubst.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GSUB/AlternateSubstFormat1.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GSUB/ChainContextSubst.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GSUB/Common.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GSUB/ContextSubst.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GSUB/ExtensionSubst.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GSUB/GSUB.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GSUB/Ligature.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GSUB/LigatureSet.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GSUB/LigatureSubst.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GSUB/LigatureSubstFormat1.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GSUB/MultipleSubst.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GSUB/MultipleSubstFormat1.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GSUB/ReverseChainSingleSubst.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GSUB/ReverseChainSingleSubstFormat1.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GSUB/Sequence.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GSUB/SingleSubst.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GSUB/SingleSubstFormat1.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GSUB/SingleSubstFormat2.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GSUB/SubstLookup.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/GSUB/SubstLookupSubTable.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/Layout/types.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/glyf/CompositeGlyph.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/glyf/Glyph.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/glyf/GlyphHeader.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/glyf/SimpleGlyph.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/glyf/SubsetGlyph.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/glyf/VarCompositeGlyph.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/glyf/composite-iter.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/glyf/coord-setter.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/glyf/glyf-helpers.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/glyf/glyf.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/glyf/loca.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/glyf/path-builder.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/OT/name/name.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/graph/classdef-graph.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/graph/coverage-graph.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/graph/graph.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/graph/gsubgpos-context.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/graph/gsubgpos-graph.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/graph/markbasepos-graph.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/graph/pairpos-graph.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/graph/serialize.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/graph/split-helpers.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-aat-layout-ankr-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-aat-layout-bsln-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-aat-layout-common.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-aat-layout-feat-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-aat-layout-just-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-aat-layout-kerx-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-aat-layout-morx-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-aat-layout-opbd-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-aat-layout-trak-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-aat-layout.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-aat-ltag-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-aat-map.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-algs.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-array.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-atomic.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-bimap.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-bit-page.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-bit-set-invertible.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-bit-set.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-blob.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-buffer-deserialize-json.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-buffer-deserialize-text-glyphs.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-buffer-deserialize-text-unicode.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-buffer.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-cache.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-cairo-utils.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-cff-interp-common.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-cff-interp-cs-common.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-cff-interp-dict-common.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-cff1-interp-cs.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-cff2-interp-cs.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-config.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-cplusplus.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-debug.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-dispatch.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-draw.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-face.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-font.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ft-colr.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-iter.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-kern.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-limits.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-machinery.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-map.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-meta.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ms-feature-ranges.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-multimap.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-mutex.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-null.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-number-parser.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-number.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-object.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-open-file.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-open-type.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-cff-common.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-cff1-std-str.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-cff1-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-cff2-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-cmap-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-face-table-list.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-face.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-gasp-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-glyf-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-hdmx-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-head-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-hhea-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-hmtx-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-kern-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-layout-base-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-layout-common.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-layout-gdef-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-layout-gpos-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-layout-gsub-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-layout-gsubgpos.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-layout-jstf-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-layout.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-map.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-math-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-maxp-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-meta-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-metrics.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-name-language-static.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-name-language.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-name-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-os2-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-os2-unicode-ranges.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-post-macroman.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-post-table-v2subset.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-post-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shape-fallback.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shape-normalize.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shape.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-arabic-fallback.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-arabic-joining-list.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-arabic-pua.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-arabic-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-arabic-win1256.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-arabic.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-indic-machine.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-indic.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-khmer-machine.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-myanmar-machine.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-syllabic.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-use-machine.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-use-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-vowel-constraints.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-stat-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-tag-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-var-avar-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-var-common.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-var-cvar-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-var-fvar-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-var-gvar-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-var-hvar-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-var-mvar-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-vorg-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-outline.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-paint-extents.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-paint.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-pool.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-priority-queue.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-repacker.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-sanitize.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-serialize.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-set-digest.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-set.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-shape-plan.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-shaper-impl.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-shaper-list.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-shaper.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-string-array.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-subset-accelerator.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-subset-cff-common.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-subset-input.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-subset-instancer-solver.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-subset-plan-member-list.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-subset-plan.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-subset.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ucd-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-unicode-emoji-table.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-unicode.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-utf.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-vector.hh
#        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-wasm-api-blob.hh
#        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-wasm-api-buffer.hh
#        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-wasm-api-common.hh
#        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-wasm-api-face.hh
#        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-wasm-api-font.hh
#        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-wasm-api-list.hh
#        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-wasm-api-shape.hh
#        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-wasm-api.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb.hh
        ${rive-harfbuzz-download_SOURCE_DIR}/src/graph/gsubgpos-context.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/graph/test-classdef-graph.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/harfbuzz-subset.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/harfbuzz.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-aat-layout.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-aat-map.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-blob.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-buffer-serialize.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-buffer-verify.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-buffer.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-cairo-utils.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-cairo.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-common.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-coretext.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-directwrite.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-draw.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-face-builder.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-face.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-fallback-shape.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-font.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ft.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-gdi.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-glib.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-gobject-structs.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-graphite2.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-icu.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-map.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-number.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-cff1-table.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-cff2-table.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-color.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-face.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-font.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-layout.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-map.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-math.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-meta.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-metrics.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-name.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shape-fallback.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shape-normalize.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shape.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-arabic.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-default.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-hangul.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-hebrew.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-indic-table.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-indic.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-khmer.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-myanmar.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-syllabic.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-thai.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-use.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-shaper-vowel-constraints.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-tag.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ot-var.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-outline.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-paint-extents.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-paint.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-set.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-shape-plan.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-shape.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-shaper.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-static.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-style.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-subset-cff-common.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-subset-cff1.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-subset-cff2.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-subset-input.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-subset-instancer-solver.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-subset-plan.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-subset-repacker.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-subset.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-ucd.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-unicode.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-uniscribe.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-wasm-api.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/hb-wasm-shape.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/main.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-algs.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-array.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-bimap.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-buffer-serialize.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-gpos-size-params.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-gsub-get-alternates.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-gsub-would-substitute.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-item-varstore.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-iter.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-machinery.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-map.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-multimap.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-number.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-ot-glyphname.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-ot-meta.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-ot-name.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-priority-queue.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-repacker.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-serialize.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-set.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-subset-instancer-solver.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-tuple-varstore.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-unicode-ranges.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-use-table.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test-vector.cc
        ${rive-harfbuzz-download_SOURCE_DIR}/src/test.cc
#        ${rive-harfbuzz-download_SOURCE_DIR}/src/wasm/graphite/shape.cc
#        ${rive-harfbuzz-download_SOURCE_DIR}/src/wasm/sample/c/shape-fallback.cc
#        ${rive-harfbuzz-download_SOURCE_DIR}/src/wasm/sample/c/shape-ot.cc
)

# ref: https://github.com/rive-app/rive-cpp/blob/4aeeaddf4aa621fdcdd48a85bb287d5c24ab9f27/dependencies/premake5_harfbuzz_v2.lua#L227
target_compile_definitions(rive-harfbuzz PUBLIC
        HB_ONLY_ONE_SHAPER # added this for Geotech Mac multi-module issue: https://github.com/rive-app/rive-cpp/issues/369
        HAVE_OT
        HB_NO_FALLBACK_SHAPE
        HB_NO_WIN1256
        HB_NO_EXTERN_HELPERS
        HB_DISABLE_DEPRECATED
        HB_NO_COLOR
        HB_NO_BITMAP
        HB_NO_BUFFER_SERIALIZE
        HB_NO_BUFFER_VERIFY
        HB_NO_BUFFER_MESSAGE
        HB_NO_SETLOCALE
        HB_NO_STYLE
        HB_NO_VERTICAL
        HB_NO_LAYOUT_COLLECT_GLYPHS
        HB_NO_LAYOUT_RARELY_USED
        HB_NO_LAYOUT_UNUSED
        HB_NO_OT_FONT_GLYPH_NAMES
        HB_NO_PAINT
        HB_NO_MMAP
        HB_NO_META
)

target_include_directories(rive-harfbuzz SYSTEM PUBLIC
        ${rive-harfbuzz-download_SOURCE_DIR}/src
)

# todo: compiler flags https://github.com/rive-app/rive-cpp/blob/6ecd5882959edd42d0e78785800216ec4c7588e2/dependencies/premake5_harfbuzz.lua#L267